seed_everything: 80085
trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 50
  accumulate_grad_batches: 8
  gradient_clip_val: 0.5
  check_val_every_n_epoch: 1
  log_every_n_steps: 5
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: ModelCheckpoint
      init_args:
        monitor: val_moda
        mode: max
        save_last: true
        save_top_k: 3
        filename: "model-e{epoch:02d}-moda{val_moda:.2f}-ap{val_ap:.2f}-c{val_best_conf:.2f}"
